### ISSUE TITLE
DFhack Updates

### ISSUE THREAD

**Issue by clinodev** [jipumarino/dfdl#9]
Hey there! 

With the recent DFhack update and two subsequent PE Starter Pack updates, is the script still updated to work? Any thoughts on adding utilities, since many of those updated as well?

Also, could you do an updated pre-prepared Mac Starter Pack again? I get asked on the subreddit a lot.

**Comment by wdifruscio** [comment]
not sure if the author is still maintaining this, I opened a PR yesterday that fixed one of the broken parts on this script.. I could fix up some of the other stuff too but I am a little unfamiliar with it all since I am a DF noob haha

@jipumarino let me know if you want some help

**Comment by jipumarino** [comment]
@wdifruscio I'm still around, but very inactive DF-wise. I'll incorporate your fix asap. Any help is welcome really.

@clinodev Sorry, for some reason I've been missing all github notifications, I'll incorporate the newest changes and get a new release in DFFD.

**Comment by jipumarino** [comment]
@wdifruscio merged!
@clinodev done!
